[package]
name = "linkding-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.1.0"
http-serde = "2.1.1"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
thiserror = "1.0.65"
ureq = { version = "2.10.1", features = ["json"] }
